### ISSUE TITLE
system_shortcuts: Errror in Android: MissingPluginException(No implementation found for method checkWifi on channel system_shortcuts)

### ISSUE THREAD

**Issue by murugadossp** [aman-malhotra-1999/SystemShortcutsFlutter#10]
On Android: 

MissingPluginException(No implementation found for method checkWifi on channel system_shortcuts)
MissingPluginException(No implementation found for method checkBluetooth on channel system_shortcuts)
Also same Error for home()

I have already added the necessary permission

   <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
     <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
     <uses-permission android:name="android.permission.BLUETOOTH"/>
     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>

try{
      bool wifiStatus = await SystemShortcuts.checkWifi;
      print("[${DateTime.now()}] currentWifi Status: $wifiStatus");
      await SystemShortcuts.wifi();
      wifiStatus = await SystemShortcuts.checkWifi;
      print("[${DateTime.now()}] currentWifi Status: $wifiStatus");
    }catch(exception){
      print("Exception Occurred on Wifi: $exception");
    }

    try{
      bool btStatus = await SystemShortcuts.checkBluetooth;
      CustomPrint.print("currentBT Status: $btStatus");
      await SystemShortcuts.bluetooth();
      btStatus = await SystemShortcuts.checkBluetooth;
      CustomPrint.print("After Toggling BT: BT Status: $btStatus");
    }catch(exception){
      print("Exception Occurred on BT: $exception");
    }

**Comment by murugadossp** [comment]
Android Version: 10

**Comment by Aman-Malhotra** [comment]
this most commonly happens when you do not re-run the flutter app . Or if you havent run flutter pub get after updating your pubspec.yaml file.
Just make sure u stop the flutter app and restart using flutter run and m sure this will be resolved.
I am closing this issue for now as it works on android 10.
You can comment on this again if you still face the issues.

**Comment by murugadossp** [comment]
After reinstalling with pub.get and reloading that issue is resolved; Even the operation is working However there is a problem

 @action
  Future<dynamic> toggleWiFi() async {
    await SystemShortcuts.wifi();
    print("After toggleWifi: ");
  }
Example this code : after the await the code does not execute the next line; 
So my requirement is toggling both wlan and BT even the below code does not work.
await SystemShortcuts.wifi();
await SystemShortcuts.bluetooth();
Can you pls check
